---
title: "Fixing plots--Week 3 lab"
author: "Galen M"
date: "January 24, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
#library(ggplot2)
library(datasets)
library(ggthemes)
head(mtcars)

#mapping = aes(color = class)

mg <- ggplot(mtcars, aes(x = mpg, y = wt)) + geom_point()
mg + facet_grid(vs + am ~ gear)

mtcars$gear <- as.character(as.numeric(mtcars$gear))
mtcars$amchar <- ifelse(mtcars$am==1, "Automatic", "Manual")
mtcars$vschar <- ifelse(mtcars$vs==1, "Straight", "V-shape")

mg5 <- ggplot(mtcars, aes(x = mpg, y = wt, color = gear)) + geom_point()
mg5 + facet_grid(vschar ~ amchar) + scale_color_colorblind() +
  labs(x = "Miles per gallon", y = "Weight (1000 lbs)", color="Gear number") + 
  theme_bw() +
  theme(legend.position=c(0.85,0.9), axis.text.x = element_text(angle=45), legend.background=element_rect(colour=NA,fill=NA)) 
ggsave(filename = "mgplot_Galen1.pdf", plot = mg5, device = pdf())
#library(cowplot)
#save_plot("mgplot_Galen.pdf", mg5, ncol = 2, nrow = 2)
mg5
```


```{r}
head(mpg)
ds <- ggplot(mpg, aes(displ, hwy, colour = class)) +
  geom_point() +
  geom_smooth() 
ds

ds2 <- ggplot(mpg, aes(displ, hwy, color = class)) +
  geom_point() +
  geom_smooth(aes(fill = class)) +
  scale_fill_colorblind() +
  scale_color_colorblind() +
  labs(x = "Engine displacement (liters)", y = "Miles per gallon") +
  theme_bw() +
  theme(legend.position=c(0.85,0.85), axis.text.x = element_text(angle=45), legend.background=element_rect(colour=NA,fill=NA))
ds2
```
